SE QUER OUTRA? N GG

MUTE le a quantidade de termos de fibonacci
CALL(N) GG

SE QUER OUTRA? x ENTAO TOMA 0 GG
SE QUER OUTRA? y ENTAO TOMA 1 GG
SE QUER OUTRA? z ENTAO TOMA 1 GG

RUSH B(N > 0){
    BANGUEI(z) GG
    x ENTAO TOMA y GG
    y ENTAO TOMA z GG
    z ENTAO TOMA x QUE OTA y GG
    N ENTAO TOMA N DROPA 1 GG
}

NO SCOPE HEADSHOT VARADO CEGO PELA SMOKE GG