SE QUER OUTRA? a GG
SE QUER OUTRA? x GG
SE QUER OUTRA? y GG

a ENTAO TOMA 0 GG

FAKE B(x ENTAO TOMA 0 GG x < 5 GG x OTA){
    FAKE B(y ENTAO TOMA 0 GG y < 5 GG y OTA){
        BANGUEI(x) GG
        BANGUEI(y) GG
    }
}


NO SCOPE HEADSHOT VARADO CEGO PELA SMOKE GG