SE QUER OUTRA? x ENTAO TOMA 0 GG
SE QUER OUTRA? y ENTAO TOMA 41 GG

ECO(y > 1){
    y ENTAO TOMA y CLUTCH 2 GG
    BANGUEI(y) GG
}

RUSH B(x < 10){
    x ENTAO TOMA x QUE OTA 1 GG
    BANGUEI x GG
}


NO SCOPE HEADSHOT VARADO CEGO PELA SMOKE GG

